### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by GamesOpenSource** [IuryAlves/RPG-Pygame#4]
```
python .\rpg.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File ".\rpg.py", line 71, in <module>
    main()
  File ".\rpg.py", line 21, in main
    personagem = Hero(20, 290, "dante", grupo)
  File "E:\Download\RPG-Pygame-master\Classes.py", line 82, in __init__
    Characters.__init__(self, start_px, start_py, image_name, *groups)
  File "E:\Download\RPG-Pygame-master\Classes.py", line 32, in __init__
    self._base_image_path + image_name + "RIGHT1.png")
pygame.error: Couldn't open sprites/danteRIGHT1.png
```

**Comment by IuryAlves** [comment]
Sorry. @GamesOpenSource 

It's been a very long time since I made this project and i cannot find the assets anymore.

You could try this one:  https://github.com/IuryAlves/pygame_demo
